displayName=Rocket.Chat Connector
author=Luke Brown
description=Send game event notifications to a self-hosted Rocket.Chat channel via webhook
tags=notification,webhook,rocketchat,discord
version=1.2.0
plugins=space.covalent.rocketchat.RocketChatConnectorPlugin
build=standard